// School photographs served from public.
export const IMAGES = {
  hero: "/hero.png",
  crest: "/crest.jpg",
  school: "/school.jpeg",
  classroom: "/pre-school2.jpeg",
  preschool_group: "/pre-school1.jpeg",
  preschool_activity: "/pre-school3.jpeg",
  sports_team: "/sports1.jpeg",
  sports_coaching: "/sports2.jpeg",
  sports_activity: "/sports3.jpeg",
  sports_group: "/sports1.jpeg",
  graduation_award: "/graduation1.jpeg",
  graduation_group: "/graduation2.jpeg",
  graduation_performance: "/graduation3.jpeg",
  graduates_celebrate: "/graduation4.jpeg",
  graduation_certificate: "/graduation5.jpeg",
  culture: "/culture.jpeg",
  cultural_procession: "/culture3.jpeg",
  cadets: "/cadet.jpeg",
  cadet_ceremony: "/cadet2.jpeg",
  career_day: "/career-dat.jpeg",
  career_group: "/career4.jpeg",
  dance: "/extra-curriculum1.jpeg",
  dance_performance: "/extra-curriculum2.jpeg",
  about: "/about.png",
} as const;
